// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Model.Models;

public partial class BazaContext : DbContext
{
    public BazaContext(DbContextOptions<BazaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SolarPanel> SolarPanels { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SolarPanel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__solar_pa__3214EC074E5019C3");

            entity.ToTable("solar_panel");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}