// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class SolarPanel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double? Power { get; set; }

    public double? Efficiency { get; set; }

    public int? Count { get; set; }
}